"""Finite audits for saturated nonadjacent spherical-shell resonances.

For lower degree ell, upper degree L, and multiplier degree J=ell+L,
this computes the resonant off-diagonal coupling matrices and the real
Lie algebra generated by their two quadratures.  It is an audit only;
the publication proof uses the representation-theoretic argument.
"""

import math
import sys

import numpy as np

from resonant_shell_lie_test import gaunt_coefficient, lie_dimension


def complex_profile_coupling(ell: int, upper: int, harmonic: int) -> np.ndarray:
    degree = ell + upper
    matrix = np.zeros((2 * upper + 1, 2 * ell + 1), dtype=complex)
    for upper_m in range(-upper, upper + 1):
        for lower_m in range(-ell, ell + 1):
            if -upper_m + harmonic + lower_m != 0:
                continue
            value = ((-1) ** upper_m) * gaunt_coefficient(
                upper,
                degree,
                ell,
                -upper_m,
                harmonic,
                lower_m,
            )
            matrix[upper_m + upper, lower_m + ell] = complex(value)
    return matrix


def off_diagonal_hermitian(coupling: np.ndarray) -> np.ndarray:
    upper_dim, lower_dim = coupling.shape
    result = np.zeros((lower_dim + upper_dim, lower_dim + upper_dim), dtype=complex)
    result[lower_dim:, :lower_dim] = coupling
    result[:lower_dim, lower_dim:] = coupling.conj().T
    return result


def resonant_real_profile_controls(ell: int, upper: int) -> list[np.ndarray]:
    degree = ell + upper
    couplings = {
        n: complex_profile_coupling(ell, upper, n)
        for n in range(-degree, degree + 1)
    }
    base_controls = [off_diagonal_hermitian(couplings[0])]
    for n in range(1, degree + 1):
        cosine = (couplings[n] + ((-1) ** n) * couplings[-n]) / math.sqrt(2)
        sine = (couplings[n] - ((-1) ** n) * couplings[-n]) / (
            1j * math.sqrt(2)
        )
        base_controls.append(off_diagonal_hermitian(cosine))
        base_controls.append(off_diagonal_hermitian(sine))
    controls = []
    lower_dim = 2 * ell + 1
    for control in base_controls:
        coupling = control[lower_dim:, :lower_dim]
        phase_coupling = 1j * coupling
        controls.append(control)
        controls.append(off_diagonal_hermitian(phase_coupling))
    return controls


def audit(ell: int, upper: int) -> None:
    lower_dim = 2 * ell + 1
    upper_dim = 2 * upper + 1
    total_dim = lower_dim + upper_dim
    controls = resonant_real_profile_controls(ell, upper)
    generators = [1j * control for control in controls]
    dimension = lie_dimension(generators)
    print(
        f"ell={ell} L={upper} J={ell + upper} dim={total_dim} "
        f"controls={len(controls)} Lie-dim={dimension} "
        f"su={total_dim**2 - 1}"
    )


if __name__ == "__main__":
    pairs = [(0, 2), (1, 3), (2, 4)]
    if len(sys.argv) > 1:
        if (len(sys.argv) - 1) % 2:
            raise SystemExit("Pass pairs: ell L [ell L ...]")
        pairs = [
            (int(sys.argv[index]), int(sys.argv[index + 1]))
            for index in range(1, len(sys.argv), 2)
        ]
    for pair in pairs:
        audit(*pair)
